name = "mutexada"
description = "mutex in ada"
version = "0.1.0-dev"

authors = ["Johnny Ngo Nguyen"]
maintainers = ["Johnny Ngo Nguyen <nguyenjohnnyngo@gmail.com>"]
maintainers-logins = ["johnnynogo"]
licenses = "MIT"
website = ""
tags = ["mutex", "ada", "realtime"]

executables = ["mutexada"]
